---

# who is the agent - name

- hosts: web

# we need detail info about the server
  gather_facts: yes

# we need sudo access become = true
  become: true

# instructions to set up nginx web server in web-agent-node
  tasks:

  - name: Install nodejs
    apt: pkg=nodejs state=present

  - name: Install npm
    apt: pkg=npm state=present
    become: true

  - name: Cloning GIT
    git:
      repo: https://github.com/snaaleeye/eng114_dev_ops
      dest: /home/vagrant/repo
      clone: yes
      update: yes

  - name: Copy default file to web server
    ansible.builtin.copy:
      src: /etc/ansible/default
      dest: /etc/nginx/sites-available/default

  - name: restart nginx
    service: name=nginx state=restarted enabled=yes


  - name: Add mongodb env var
    shell: source /home/vagrant/.bashrc && echo export DB_HOST=mongodb://192.168.56.15:27017/posts >> /home/vagrant/.bashrc
    args:
      executable: /bin/bash


