# who is the agent - name

- hosts: web

# we need detail info about the server
  gather_facts: yes

# we need sudo access become = true
  become: true

# instructions to set up nginx web server in web-agent-node
  tasks:
  - name: Install Nginx Web server
    apt: pkg=nginx state=present

# we need to ensure that nginx is running

