---

- hosts: web
  gather_facts: yes
  become: true

  tasks:
    - name: Copying the default file
      copy:
        src: ~/default
        dest: /etc/nginx/sites-available/default

    - name: restart nginx
      service: name=nginx state=restarted enabled=yes
