
---

- hosts: app
  gather_facts: yes
  become: true

  tasks:
  - name: Install Nginx Web server
    apt: pkg=nginx state=present
  - name: restart nginx
    service: name=nginx state=restarted enabled=yes
  tags: ['never', 'nginx']
