---
- hosts: db
  gather_facts: yes
  become: true

  #install mongodb
  #copy over config file
  #restart mongodb
  tasks:
  - name: Installing Mongodb
    apt: pkg=mongodb state=present
  - name: Changing Mongo.conf file
    copy:
      src: etc/ansible/ansible/app/app/mongodb.conf
      dest: /etc/mongodb.conf
  - name: Restarting Mongo
    ansible.builtin.service:
      name: mongodb
      state: restarted
      enabled: true
